install common packages:
  pkg.installed:
    - pkgs:
      - base-devel
      - python-virtualenv
      - unzip
      - curl
      - nmap
      - automake
      - make
      - htop
      - iftop
      - sysstat
      - task
      - irssi
      - ctags
      - git
      - screen
      - xclip
      - strace
      - feh
    - refresh: true
